[package]
name = "dvs-decoder"
version.workspace = true
edition.workspace = true

[dependencies]
dvs-media.workspace = true
dvs-gpu.workspace = true
thiserror.workspace = true

[target.'cfg(windows)'.dependencies]
ffmpeg-sys-next = "8"
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi",
] }

[dev-dependencies]
pollster = "0.4"
winit = "0.30"
wgpu.workspace = true
